// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/socklabs/elasticservices/core/service.proto

package org.socklabs.elasticservices.core;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ComponentRefOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string site = 1;
    boolean hasSite();
    String getSite();
    
    // optional string cluster = 2;
    boolean hasCluster();
    String getCluster();
    
    // optional string component_id = 3;
    boolean hasComponentId();
    String getComponentId();
  }
  public static final class ComponentRef extends
      com.google.protobuf.GeneratedMessage
      implements ComponentRefOrBuilder {
    // Use ComponentRef.newBuilder() to construct.
    private ComponentRef(Builder builder) {
      super(builder);
    }
    private ComponentRef(boolean noInit) {}
    
    private static final ComponentRef defaultInstance;
    public static ComponentRef getDefaultInstance() {
      return defaultInstance;
    }
    
    public ComponentRef getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ComponentRef_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ComponentRef_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string site = 1;
    public static final int SITE_FIELD_NUMBER = 1;
    private java.lang.Object site_;
    public boolean hasSite() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getSite() {
      java.lang.Object ref = site_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          site_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSiteBytes() {
      java.lang.Object ref = site_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        site_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string cluster = 2;
    public static final int CLUSTER_FIELD_NUMBER = 2;
    private java.lang.Object cluster_;
    public boolean hasCluster() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getCluster() {
      java.lang.Object ref = cluster_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          cluster_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClusterBytes() {
      java.lang.Object ref = cluster_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        cluster_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string component_id = 3;
    public static final int COMPONENT_ID_FIELD_NUMBER = 3;
    private java.lang.Object componentId_;
    public boolean hasComponentId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getComponentId() {
      java.lang.Object ref = componentId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          componentId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getComponentIdBytes() {
      java.lang.Object ref = componentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        componentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      site_ = "";
      cluster_ = "";
      componentId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSiteBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getClusterBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getComponentIdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSiteBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getClusterBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getComponentIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.socklabs.elasticservices.core.ServiceProto.ComponentRef parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ComponentRef parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ComponentRef parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ComponentRef parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ComponentRef parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ComponentRef parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ComponentRef parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ComponentRef parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ComponentRef parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ComponentRef parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.socklabs.elasticservices.core.ServiceProto.ComponentRef prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.socklabs.elasticservices.core.ServiceProto.ComponentRefOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ComponentRef_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ComponentRef_fieldAccessorTable;
      }
      
      // Construct using org.socklabs.elasticservices.core.ServiceProto.ComponentRef.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        site_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cluster_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        componentId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.socklabs.elasticservices.core.ServiceProto.ComponentRef.getDescriptor();
      }
      
      public org.socklabs.elasticservices.core.ServiceProto.ComponentRef getDefaultInstanceForType() {
        return org.socklabs.elasticservices.core.ServiceProto.ComponentRef.getDefaultInstance();
      }
      
      public org.socklabs.elasticservices.core.ServiceProto.ComponentRef build() {
        org.socklabs.elasticservices.core.ServiceProto.ComponentRef result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.socklabs.elasticservices.core.ServiceProto.ComponentRef buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.socklabs.elasticservices.core.ServiceProto.ComponentRef result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.socklabs.elasticservices.core.ServiceProto.ComponentRef buildPartial() {
        org.socklabs.elasticservices.core.ServiceProto.ComponentRef result = new org.socklabs.elasticservices.core.ServiceProto.ComponentRef(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.site_ = site_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cluster_ = cluster_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.componentId_ = componentId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.socklabs.elasticservices.core.ServiceProto.ComponentRef) {
          return mergeFrom((org.socklabs.elasticservices.core.ServiceProto.ComponentRef)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.socklabs.elasticservices.core.ServiceProto.ComponentRef other) {
        if (other == org.socklabs.elasticservices.core.ServiceProto.ComponentRef.getDefaultInstance()) return this;
        if (other.hasSite()) {
          setSite(other.getSite());
        }
        if (other.hasCluster()) {
          setCluster(other.getCluster());
        }
        if (other.hasComponentId()) {
          setComponentId(other.getComponentId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              site_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              cluster_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              componentId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string site = 1;
      private java.lang.Object site_ = "";
      public boolean hasSite() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getSite() {
        java.lang.Object ref = site_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          site_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSite(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        site_ = value;
        onChanged();
        return this;
      }
      public Builder clearSite() {
        bitField0_ = (bitField0_ & ~0x00000001);
        site_ = getDefaultInstance().getSite();
        onChanged();
        return this;
      }
      void setSite(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        site_ = value;
        onChanged();
      }
      
      // optional string cluster = 2;
      private java.lang.Object cluster_ = "";
      public boolean hasCluster() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getCluster() {
        java.lang.Object ref = cluster_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          cluster_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCluster(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cluster_ = value;
        onChanged();
        return this;
      }
      public Builder clearCluster() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cluster_ = getDefaultInstance().getCluster();
        onChanged();
        return this;
      }
      void setCluster(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        cluster_ = value;
        onChanged();
      }
      
      // optional string component_id = 3;
      private java.lang.Object componentId_ = "";
      public boolean hasComponentId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getComponentId() {
        java.lang.Object ref = componentId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          componentId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setComponentId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        componentId_ = value;
        onChanged();
        return this;
      }
      public Builder clearComponentId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        componentId_ = getDefaultInstance().getComponentId();
        onChanged();
        return this;
      }
      void setComponentId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        componentId_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.socklabs.elasticservices.core.ComponentRef)
    }
    
    static {
      defaultInstance = new ComponentRef(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.socklabs.elasticservices.core.ComponentRef)
  }
  
  public interface ServiceRefOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .org.socklabs.elasticservices.core.ComponentRef component_ref = 1;
    boolean hasComponentRef();
    org.socklabs.elasticservices.core.ServiceProto.ComponentRef getComponentRef();
    org.socklabs.elasticservices.core.ServiceProto.ComponentRefOrBuilder getComponentRefOrBuilder();
    
    // optional string service_id = 2;
    boolean hasServiceId();
    String getServiceId();
  }
  public static final class ServiceRef extends
      com.google.protobuf.GeneratedMessage
      implements ServiceRefOrBuilder {
    // Use ServiceRef.newBuilder() to construct.
    private ServiceRef(Builder builder) {
      super(builder);
    }
    private ServiceRef(boolean noInit) {}
    
    private static final ServiceRef defaultInstance;
    public static ServiceRef getDefaultInstance() {
      return defaultInstance;
    }
    
    public ServiceRef getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ServiceRef_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ServiceRef_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .org.socklabs.elasticservices.core.ComponentRef component_ref = 1;
    public static final int COMPONENT_REF_FIELD_NUMBER = 1;
    private org.socklabs.elasticservices.core.ServiceProto.ComponentRef componentRef_;
    public boolean hasComponentRef() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.socklabs.elasticservices.core.ServiceProto.ComponentRef getComponentRef() {
      return componentRef_;
    }
    public org.socklabs.elasticservices.core.ServiceProto.ComponentRefOrBuilder getComponentRefOrBuilder() {
      return componentRef_;
    }
    
    // optional string service_id = 2;
    public static final int SERVICE_ID_FIELD_NUMBER = 2;
    private java.lang.Object serviceId_;
    public boolean hasServiceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getServiceId() {
      java.lang.Object ref = serviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          serviceId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getServiceIdBytes() {
      java.lang.Object ref = serviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        serviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      componentRef_ = org.socklabs.elasticservices.core.ServiceProto.ComponentRef.getDefaultInstance();
      serviceId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, componentRef_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getServiceIdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, componentRef_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getServiceIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.socklabs.elasticservices.core.ServiceProto.ServiceRef parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ServiceRef parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ServiceRef parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ServiceRef parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ServiceRef parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ServiceRef parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ServiceRef parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ServiceRef parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ServiceRef parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ServiceRef parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.socklabs.elasticservices.core.ServiceProto.ServiceRef prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.socklabs.elasticservices.core.ServiceProto.ServiceRefOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ServiceRef_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ServiceRef_fieldAccessorTable;
      }
      
      // Construct using org.socklabs.elasticservices.core.ServiceProto.ServiceRef.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getComponentRefFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (componentRefBuilder_ == null) {
          componentRef_ = org.socklabs.elasticservices.core.ServiceProto.ComponentRef.getDefaultInstance();
        } else {
          componentRefBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.socklabs.elasticservices.core.ServiceProto.ServiceRef.getDescriptor();
      }
      
      public org.socklabs.elasticservices.core.ServiceProto.ServiceRef getDefaultInstanceForType() {
        return org.socklabs.elasticservices.core.ServiceProto.ServiceRef.getDefaultInstance();
      }
      
      public org.socklabs.elasticservices.core.ServiceProto.ServiceRef build() {
        org.socklabs.elasticservices.core.ServiceProto.ServiceRef result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.socklabs.elasticservices.core.ServiceProto.ServiceRef buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.socklabs.elasticservices.core.ServiceProto.ServiceRef result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.socklabs.elasticservices.core.ServiceProto.ServiceRef buildPartial() {
        org.socklabs.elasticservices.core.ServiceProto.ServiceRef result = new org.socklabs.elasticservices.core.ServiceProto.ServiceRef(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (componentRefBuilder_ == null) {
          result.componentRef_ = componentRef_;
        } else {
          result.componentRef_ = componentRefBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serviceId_ = serviceId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.socklabs.elasticservices.core.ServiceProto.ServiceRef) {
          return mergeFrom((org.socklabs.elasticservices.core.ServiceProto.ServiceRef)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.socklabs.elasticservices.core.ServiceProto.ServiceRef other) {
        if (other == org.socklabs.elasticservices.core.ServiceProto.ServiceRef.getDefaultInstance()) return this;
        if (other.hasComponentRef()) {
          mergeComponentRef(other.getComponentRef());
        }
        if (other.hasServiceId()) {
          setServiceId(other.getServiceId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.socklabs.elasticservices.core.ServiceProto.ComponentRef.Builder subBuilder = org.socklabs.elasticservices.core.ServiceProto.ComponentRef.newBuilder();
              if (hasComponentRef()) {
                subBuilder.mergeFrom(getComponentRef());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setComponentRef(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              serviceId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .org.socklabs.elasticservices.core.ComponentRef component_ref = 1;
      private org.socklabs.elasticservices.core.ServiceProto.ComponentRef componentRef_ = org.socklabs.elasticservices.core.ServiceProto.ComponentRef.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.socklabs.elasticservices.core.ServiceProto.ComponentRef, org.socklabs.elasticservices.core.ServiceProto.ComponentRef.Builder, org.socklabs.elasticservices.core.ServiceProto.ComponentRefOrBuilder> componentRefBuilder_;
      public boolean hasComponentRef() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.socklabs.elasticservices.core.ServiceProto.ComponentRef getComponentRef() {
        if (componentRefBuilder_ == null) {
          return componentRef_;
        } else {
          return componentRefBuilder_.getMessage();
        }
      }
      public Builder setComponentRef(org.socklabs.elasticservices.core.ServiceProto.ComponentRef value) {
        if (componentRefBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          componentRef_ = value;
          onChanged();
        } else {
          componentRefBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setComponentRef(
          org.socklabs.elasticservices.core.ServiceProto.ComponentRef.Builder builderForValue) {
        if (componentRefBuilder_ == null) {
          componentRef_ = builderForValue.build();
          onChanged();
        } else {
          componentRefBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeComponentRef(org.socklabs.elasticservices.core.ServiceProto.ComponentRef value) {
        if (componentRefBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              componentRef_ != org.socklabs.elasticservices.core.ServiceProto.ComponentRef.getDefaultInstance()) {
            componentRef_ =
              org.socklabs.elasticservices.core.ServiceProto.ComponentRef.newBuilder(componentRef_).mergeFrom(value).buildPartial();
          } else {
            componentRef_ = value;
          }
          onChanged();
        } else {
          componentRefBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearComponentRef() {
        if (componentRefBuilder_ == null) {
          componentRef_ = org.socklabs.elasticservices.core.ServiceProto.ComponentRef.getDefaultInstance();
          onChanged();
        } else {
          componentRefBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public org.socklabs.elasticservices.core.ServiceProto.ComponentRef.Builder getComponentRefBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getComponentRefFieldBuilder().getBuilder();
      }
      public org.socklabs.elasticservices.core.ServiceProto.ComponentRefOrBuilder getComponentRefOrBuilder() {
        if (componentRefBuilder_ != null) {
          return componentRefBuilder_.getMessageOrBuilder();
        } else {
          return componentRef_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.socklabs.elasticservices.core.ServiceProto.ComponentRef, org.socklabs.elasticservices.core.ServiceProto.ComponentRef.Builder, org.socklabs.elasticservices.core.ServiceProto.ComponentRefOrBuilder> 
          getComponentRefFieldBuilder() {
        if (componentRefBuilder_ == null) {
          componentRefBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.socklabs.elasticservices.core.ServiceProto.ComponentRef, org.socklabs.elasticservices.core.ServiceProto.ComponentRef.Builder, org.socklabs.elasticservices.core.ServiceProto.ComponentRefOrBuilder>(
                  componentRef_,
                  getParentForChildren(),
                  isClean());
          componentRef_ = null;
        }
        return componentRefBuilder_;
      }
      
      // optional string service_id = 2;
      private java.lang.Object serviceId_ = "";
      public boolean hasServiceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getServiceId() {
        java.lang.Object ref = serviceId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          serviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setServiceId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serviceId_ = value;
        onChanged();
        return this;
      }
      public Builder clearServiceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serviceId_ = getDefaultInstance().getServiceId();
        onChanged();
        return this;
      }
      void setServiceId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        serviceId_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.socklabs.elasticservices.core.ServiceRef)
    }
    
    static {
      defaultInstance = new ServiceRef(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.socklabs.elasticservices.core.ServiceRef)
  }
  
  public interface ContentTypeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string value = 1;
    boolean hasValue();
    String getValue();
    
    // repeated .org.socklabs.elasticservices.core.ContentType.Attribute attribute = 2;
    java.util.List<org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute> 
        getAttributeList();
    org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute getAttribute(int index);
    int getAttributeCount();
    java.util.List<? extends org.socklabs.elasticservices.core.ServiceProto.ContentType.AttributeOrBuilder> 
        getAttributeOrBuilderList();
    org.socklabs.elasticservices.core.ServiceProto.ContentType.AttributeOrBuilder getAttributeOrBuilder(
        int index);
  }
  public static final class ContentType extends
      com.google.protobuf.GeneratedMessage
      implements ContentTypeOrBuilder {
    // Use ContentType.newBuilder() to construct.
    private ContentType(Builder builder) {
      super(builder);
    }
    private ContentType(boolean noInit) {}
    
    private static final ContentType defaultInstance;
    public static ContentType getDefaultInstance() {
      return defaultInstance;
    }
    
    public ContentType getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ContentType_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ContentType_fieldAccessorTable;
    }
    
    public interface AttributeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional string key = 1;
      boolean hasKey();
      String getKey();
      
      // optional string value = 2;
      boolean hasValue();
      String getValue();
    }
    public static final class Attribute extends
        com.google.protobuf.GeneratedMessage
        implements AttributeOrBuilder {
      // Use Attribute.newBuilder() to construct.
      private Attribute(Builder builder) {
        super(builder);
      }
      private Attribute(boolean noInit) {}
      
      private static final Attribute defaultInstance;
      public static Attribute getDefaultInstance() {
        return defaultInstance;
      }
      
      public Attribute getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ContentType_Attribute_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ContentType_Attribute_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            key_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            value_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        key_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.socklabs.elasticservices.core.ServiceProto.ContentType.AttributeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ContentType_Attribute_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ContentType_Attribute_fieldAccessorTable;
        }
        
        // Construct using org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.getDescriptor();
        }
        
        public org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute getDefaultInstanceForType() {
          return org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.getDefaultInstance();
        }
        
        public org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute build() {
          org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute buildPartial() {
          org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute result = new org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute) {
            return mergeFrom((org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute other) {
          if (other == org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.getDefaultInstance()) return this;
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional string key = 1;
        private java.lang.Object key_ = "";
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setKey(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        void setKey(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
        }
        
        // optional string value = 2;
        private java.lang.Object value_ = "";
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setValue(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        void setValue(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:org.socklabs.elasticservices.core.ContentType.Attribute)
      }
      
      static {
        defaultInstance = new Attribute(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:org.socklabs.elasticservices.core.ContentType.Attribute)
    }
    
    private int bitField0_;
    // optional string value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .org.socklabs.elasticservices.core.ContentType.Attribute attribute = 2;
    public static final int ATTRIBUTE_FIELD_NUMBER = 2;
    private java.util.List<org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute> attribute_;
    public java.util.List<org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute> getAttributeList() {
      return attribute_;
    }
    public java.util.List<? extends org.socklabs.elasticservices.core.ServiceProto.ContentType.AttributeOrBuilder> 
        getAttributeOrBuilderList() {
      return attribute_;
    }
    public int getAttributeCount() {
      return attribute_.size();
    }
    public org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute getAttribute(int index) {
      return attribute_.get(index);
    }
    public org.socklabs.elasticservices.core.ServiceProto.ContentType.AttributeOrBuilder getAttributeOrBuilder(
        int index) {
      return attribute_.get(index);
    }
    
    private void initFields() {
      value_ = "";
      attribute_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getValueBytes());
      }
      for (int i = 0; i < attribute_.size(); i++) {
        output.writeMessage(2, attribute_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getValueBytes());
      }
      for (int i = 0; i < attribute_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, attribute_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.socklabs.elasticservices.core.ServiceProto.ContentType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ContentType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ContentType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ContentType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ContentType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ContentType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ContentType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ContentType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ContentType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.socklabs.elasticservices.core.ServiceProto.ContentType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.socklabs.elasticservices.core.ServiceProto.ContentType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.socklabs.elasticservices.core.ServiceProto.ContentTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ContentType_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.socklabs.elasticservices.core.ServiceProto.internal_static_org_socklabs_elasticservices_core_ContentType_fieldAccessorTable;
      }
      
      // Construct using org.socklabs.elasticservices.core.ServiceProto.ContentType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttributeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (attributeBuilder_ == null) {
          attribute_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          attributeBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.socklabs.elasticservices.core.ServiceProto.ContentType.getDescriptor();
      }
      
      public org.socklabs.elasticservices.core.ServiceProto.ContentType getDefaultInstanceForType() {
        return org.socklabs.elasticservices.core.ServiceProto.ContentType.getDefaultInstance();
      }
      
      public org.socklabs.elasticservices.core.ServiceProto.ContentType build() {
        org.socklabs.elasticservices.core.ServiceProto.ContentType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.socklabs.elasticservices.core.ServiceProto.ContentType buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.socklabs.elasticservices.core.ServiceProto.ContentType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.socklabs.elasticservices.core.ServiceProto.ContentType buildPartial() {
        org.socklabs.elasticservices.core.ServiceProto.ContentType result = new org.socklabs.elasticservices.core.ServiceProto.ContentType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        if (attributeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            attribute_ = java.util.Collections.unmodifiableList(attribute_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.attribute_ = attribute_;
        } else {
          result.attribute_ = attributeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.socklabs.elasticservices.core.ServiceProto.ContentType) {
          return mergeFrom((org.socklabs.elasticservices.core.ServiceProto.ContentType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.socklabs.elasticservices.core.ServiceProto.ContentType other) {
        if (other == org.socklabs.elasticservices.core.ServiceProto.ContentType.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (attributeBuilder_ == null) {
          if (!other.attribute_.isEmpty()) {
            if (attribute_.isEmpty()) {
              attribute_ = other.attribute_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAttributeIsMutable();
              attribute_.addAll(other.attribute_);
            }
            onChanged();
          }
        } else {
          if (!other.attribute_.isEmpty()) {
            if (attributeBuilder_.isEmpty()) {
              attributeBuilder_.dispose();
              attributeBuilder_ = null;
              attribute_ = other.attribute_;
              bitField0_ = (bitField0_ & ~0x00000002);
              attributeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttributeFieldBuilder() : null;
            } else {
              attributeBuilder_.addAllMessages(other.attribute_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              value_ = input.readBytes();
              break;
            }
            case 18: {
              org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.Builder subBuilder = org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAttribute(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string value = 1;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
      }
      
      // repeated .org.socklabs.elasticservices.core.ContentType.Attribute attribute = 2;
      private java.util.List<org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute> attribute_ =
        java.util.Collections.emptyList();
      private void ensureAttributeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          attribute_ = new java.util.ArrayList<org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute>(attribute_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute, org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.Builder, org.socklabs.elasticservices.core.ServiceProto.ContentType.AttributeOrBuilder> attributeBuilder_;
      
      public java.util.List<org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute> getAttributeList() {
        if (attributeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attribute_);
        } else {
          return attributeBuilder_.getMessageList();
        }
      }
      public int getAttributeCount() {
        if (attributeBuilder_ == null) {
          return attribute_.size();
        } else {
          return attributeBuilder_.getCount();
        }
      }
      public org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute getAttribute(int index) {
        if (attributeBuilder_ == null) {
          return attribute_.get(index);
        } else {
          return attributeBuilder_.getMessage(index);
        }
      }
      public Builder setAttribute(
          int index, org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeIsMutable();
          attribute_.set(index, value);
          onChanged();
        } else {
          attributeBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAttribute(
          int index, org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAttribute(org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeIsMutable();
          attribute_.add(value);
          onChanged();
        } else {
          attributeBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAttribute(
          int index, org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeIsMutable();
          attribute_.add(index, value);
          onChanged();
        } else {
          attributeBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAttribute(
          org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.add(builderForValue.build());
          onChanged();
        } else {
          attributeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAttribute(
          int index, org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAttribute(
          java.lang.Iterable<? extends org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute> values) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          super.addAll(values, attribute_);
          onChanged();
        } else {
          attributeBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAttribute() {
        if (attributeBuilder_ == null) {
          attribute_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          attributeBuilder_.clear();
        }
        return this;
      }
      public Builder removeAttribute(int index) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.remove(index);
          onChanged();
        } else {
          attributeBuilder_.remove(index);
        }
        return this;
      }
      public org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.Builder getAttributeBuilder(
          int index) {
        return getAttributeFieldBuilder().getBuilder(index);
      }
      public org.socklabs.elasticservices.core.ServiceProto.ContentType.AttributeOrBuilder getAttributeOrBuilder(
          int index) {
        if (attributeBuilder_ == null) {
          return attribute_.get(index);  } else {
          return attributeBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.socklabs.elasticservices.core.ServiceProto.ContentType.AttributeOrBuilder> 
           getAttributeOrBuilderList() {
        if (attributeBuilder_ != null) {
          return attributeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attribute_);
        }
      }
      public org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.Builder addAttributeBuilder() {
        return getAttributeFieldBuilder().addBuilder(
            org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.getDefaultInstance());
      }
      public org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.Builder addAttributeBuilder(
          int index) {
        return getAttributeFieldBuilder().addBuilder(
            index, org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.getDefaultInstance());
      }
      public java.util.List<org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.Builder> 
           getAttributeBuilderList() {
        return getAttributeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute, org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.Builder, org.socklabs.elasticservices.core.ServiceProto.ContentType.AttributeOrBuilder> 
          getAttributeFieldBuilder() {
        if (attributeBuilder_ == null) {
          attributeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute, org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.Builder, org.socklabs.elasticservices.core.ServiceProto.ContentType.AttributeOrBuilder>(
                  attribute_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          attribute_ = null;
        }
        return attributeBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.socklabs.elasticservices.core.ContentType)
    }
    
    static {
      defaultInstance = new ContentType(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.socklabs.elasticservices.core.ContentType)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_socklabs_elasticservices_core_ComponentRef_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_socklabs_elasticservices_core_ComponentRef_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_socklabs_elasticservices_core_ServiceRef_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_socklabs_elasticservices_core_ServiceRef_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_socklabs_elasticservices_core_ContentType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_socklabs_elasticservices_core_ContentType_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_socklabs_elasticservices_core_ContentType_Attribute_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_socklabs_elasticservices_core_ContentType_Attribute_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/org/socklabs/elasticservices/core/serv" +
      "ice.proto\022!org.socklabs.elasticservices." +
      "core\"C\n\014ComponentRef\022\014\n\004site\030\001 \001(\t\022\017\n\007cl" +
      "uster\030\002 \001(\t\022\024\n\014component_id\030\003 \001(\t\"h\n\nSer" +
      "viceRef\022F\n\rcomponent_ref\030\001 \001(\0132/.org.soc" +
      "klabs.elasticservices.core.ComponentRef\022" +
      "\022\n\nservice_id\030\002 \001(\t\"\222\001\n\013ContentType\022\r\n\005v" +
      "alue\030\001 \001(\t\022K\n\tattribute\030\002 \003(\01328.org.sock" +
      "labs.elasticservices.core.ContentType.At" +
      "tribute\032\'\n\tAttribute\022\013\n\003key\030\001 \001(\t\022\r\n\005val",
      "ue\030\002 \001(\tB6\n!org.socklabs.elasticservices" +
      ".coreB\014ServiceProtoH\001\210\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_socklabs_elasticservices_core_ComponentRef_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_socklabs_elasticservices_core_ComponentRef_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_socklabs_elasticservices_core_ComponentRef_descriptor,
              new java.lang.String[] { "Site", "Cluster", "ComponentId", },
              org.socklabs.elasticservices.core.ServiceProto.ComponentRef.class,
              org.socklabs.elasticservices.core.ServiceProto.ComponentRef.Builder.class);
          internal_static_org_socklabs_elasticservices_core_ServiceRef_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_socklabs_elasticservices_core_ServiceRef_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_socklabs_elasticservices_core_ServiceRef_descriptor,
              new java.lang.String[] { "ComponentRef", "ServiceId", },
              org.socklabs.elasticservices.core.ServiceProto.ServiceRef.class,
              org.socklabs.elasticservices.core.ServiceProto.ServiceRef.Builder.class);
          internal_static_org_socklabs_elasticservices_core_ContentType_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_socklabs_elasticservices_core_ContentType_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_socklabs_elasticservices_core_ContentType_descriptor,
              new java.lang.String[] { "Value", "Attribute", },
              org.socklabs.elasticservices.core.ServiceProto.ContentType.class,
              org.socklabs.elasticservices.core.ServiceProto.ContentType.Builder.class);
          internal_static_org_socklabs_elasticservices_core_ContentType_Attribute_descriptor =
            internal_static_org_socklabs_elasticservices_core_ContentType_descriptor.getNestedTypes().get(0);
          internal_static_org_socklabs_elasticservices_core_ContentType_Attribute_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_socklabs_elasticservices_core_ContentType_Attribute_descriptor,
              new java.lang.String[] { "Key", "Value", },
              org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.class,
              org.socklabs.elasticservices.core.ServiceProto.ContentType.Attribute.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
