// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/socklabs/elasticservices/work/work.proto

package com.socklabs.elasticservices.work;

public final class WorkServiceProto {
  private WorkServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WorkInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string id = 1;
    boolean hasId();
    String getId();
    
    // optional string phase = 2;
    boolean hasPhase();
    String getPhase();
    
    // optional bool is_shutting_down = 3;
    boolean hasIsShuttingDown();
    boolean getIsShuttingDown();
  }
  public static final class WorkInfo extends
      com.google.protobuf.GeneratedMessage
      implements WorkInfoOrBuilder {
    // Use WorkInfo.newBuilder() to construct.
    private WorkInfo(Builder builder) {
      super(builder);
    }
    private WorkInfo(boolean noInit) {}
    
    private static final WorkInfo defaultInstance;
    public static WorkInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public WorkInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socklabs.elasticservices.work.WorkServiceProto.internal_static_com_socklabs_elasticservices_work_WorkInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socklabs.elasticservices.work.WorkServiceProto.internal_static_com_socklabs_elasticservices_work_WorkInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string phase = 2;
    public static final int PHASE_FIELD_NUMBER = 2;
    private java.lang.Object phase_;
    public boolean hasPhase() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPhase() {
      java.lang.Object ref = phase_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          phase_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPhaseBytes() {
      java.lang.Object ref = phase_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        phase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool is_shutting_down = 3;
    public static final int IS_SHUTTING_DOWN_FIELD_NUMBER = 3;
    private boolean isShuttingDown_;
    public boolean hasIsShuttingDown() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getIsShuttingDown() {
      return isShuttingDown_;
    }
    
    private void initFields() {
      id_ = "";
      phase_ = "";
      isShuttingDown_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPhaseBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isShuttingDown_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPhaseBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isShuttingDown_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.socklabs.elasticservices.work.WorkServiceProto.WorkInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.socklabs.elasticservices.work.WorkServiceProto.internal_static_com_socklabs_elasticservices_work_WorkInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.socklabs.elasticservices.work.WorkServiceProto.internal_static_com_socklabs_elasticservices_work_WorkInfo_fieldAccessorTable;
      }
      
      // Construct using com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        phase_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        isShuttingDown_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.getDescriptor();
      }
      
      public com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo getDefaultInstanceForType() {
        return com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.getDefaultInstance();
      }
      
      public com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo build() {
        com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo buildPartial() {
        com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo result = new com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.phase_ = phase_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isShuttingDown_ = isShuttingDown_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo) {
          return mergeFrom((com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo other) {
        if (other == com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPhase()) {
          setPhase(other.getPhase());
        }
        if (other.hasIsShuttingDown()) {
          setIsShuttingDown(other.getIsShuttingDown());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              phase_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isShuttingDown_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // optional string phase = 2;
      private java.lang.Object phase_ = "";
      public boolean hasPhase() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPhase() {
        java.lang.Object ref = phase_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          phase_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPhase(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        phase_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhase() {
        bitField0_ = (bitField0_ & ~0x00000002);
        phase_ = getDefaultInstance().getPhase();
        onChanged();
        return this;
      }
      void setPhase(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        phase_ = value;
        onChanged();
      }
      
      // optional bool is_shutting_down = 3;
      private boolean isShuttingDown_ ;
      public boolean hasIsShuttingDown() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getIsShuttingDown() {
        return isShuttingDown_;
      }
      public Builder setIsShuttingDown(boolean value) {
        bitField0_ |= 0x00000004;
        isShuttingDown_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsShuttingDown() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isShuttingDown_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socklabs.elasticservices.work.WorkInfo)
    }
    
    static {
      defaultInstance = new WorkInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socklabs.elasticservices.work.WorkInfo)
  }
  
  public interface ListRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string id = 1;
    java.util.List<String> getIdList();
    int getIdCount();
    String getId(int index);
  }
  public static final class ListRequest extends
      com.google.protobuf.GeneratedMessage
      implements ListRequestOrBuilder {
    // Use ListRequest.newBuilder() to construct.
    private ListRequest(Builder builder) {
      super(builder);
    }
    private ListRequest(boolean noInit) {}
    
    private static final ListRequest defaultInstance;
    public static ListRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ListRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socklabs.elasticservices.work.WorkServiceProto.internal_static_com_socklabs_elasticservices_work_ListRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socklabs.elasticservices.work.WorkServiceProto.internal_static_com_socklabs_elasticservices_work_ListRequest_fieldAccessorTable;
    }
    
    // repeated string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList id_;
    public java.util.List<String>
        getIdList() {
      return id_;
    }
    public int getIdCount() {
      return id_.size();
    }
    public String getId(int index) {
      return id_.get(index);
    }
    
    private void initFields() {
      id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < id_.size(); i++) {
        output.writeBytes(1, id_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < id_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(id_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socklabs.elasticservices.work.WorkServiceProto.ListRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.socklabs.elasticservices.work.WorkServiceProto.ListRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.socklabs.elasticservices.work.WorkServiceProto.internal_static_com_socklabs_elasticservices_work_ListRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.socklabs.elasticservices.work.WorkServiceProto.internal_static_com_socklabs_elasticservices_work_ListRequest_fieldAccessorTable;
      }
      
      // Construct using com.socklabs.elasticservices.work.WorkServiceProto.ListRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socklabs.elasticservices.work.WorkServiceProto.ListRequest.getDescriptor();
      }
      
      public com.socklabs.elasticservices.work.WorkServiceProto.ListRequest getDefaultInstanceForType() {
        return com.socklabs.elasticservices.work.WorkServiceProto.ListRequest.getDefaultInstance();
      }
      
      public com.socklabs.elasticservices.work.WorkServiceProto.ListRequest build() {
        com.socklabs.elasticservices.work.WorkServiceProto.ListRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.socklabs.elasticservices.work.WorkServiceProto.ListRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.socklabs.elasticservices.work.WorkServiceProto.ListRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.socklabs.elasticservices.work.WorkServiceProto.ListRequest buildPartial() {
        com.socklabs.elasticservices.work.WorkServiceProto.ListRequest result = new com.socklabs.elasticservices.work.WorkServiceProto.ListRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = new com.google.protobuf.UnmodifiableLazyStringList(
              id_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.id_ = id_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socklabs.elasticservices.work.WorkServiceProto.ListRequest) {
          return mergeFrom((com.socklabs.elasticservices.work.WorkServiceProto.ListRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socklabs.elasticservices.work.WorkServiceProto.ListRequest other) {
        if (other == com.socklabs.elasticservices.work.WorkServiceProto.ListRequest.getDefaultInstance()) return this;
        if (!other.id_.isEmpty()) {
          if (id_.isEmpty()) {
            id_ = other.id_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdIsMutable();
            id_.addAll(other.id_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureIdIsMutable();
              id_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string id = 1;
      private com.google.protobuf.LazyStringList id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = new com.google.protobuf.LazyStringArrayList(id_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getIdList() {
        return java.util.Collections.unmodifiableList(id_);
      }
      public int getIdCount() {
        return id_.size();
      }
      public String getId(int index) {
        return id_.get(index);
      }
      public Builder setId(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
        id_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
        id_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllId(
          java.lang.Iterable<String> values) {
        ensureIdIsMutable();
        super.addAll(values, id_);
        onChanged();
        return this;
      }
      public Builder clearId() {
        id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addId(com.google.protobuf.ByteString value) {
        ensureIdIsMutable();
        id_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.socklabs.elasticservices.work.ListRequest)
    }
    
    static {
      defaultInstance = new ListRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socklabs.elasticservices.work.ListRequest)
  }
  
  public interface ListResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.socklabs.elasticservices.work.WorkInfo work_info = 1;
    java.util.List<com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo> 
        getWorkInfoList();
    com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo getWorkInfo(int index);
    int getWorkInfoCount();
    java.util.List<? extends com.socklabs.elasticservices.work.WorkServiceProto.WorkInfoOrBuilder> 
        getWorkInfoOrBuilderList();
    com.socklabs.elasticservices.work.WorkServiceProto.WorkInfoOrBuilder getWorkInfoOrBuilder(
        int index);
  }
  public static final class ListResponse extends
      com.google.protobuf.GeneratedMessage
      implements ListResponseOrBuilder {
    // Use ListResponse.newBuilder() to construct.
    private ListResponse(Builder builder) {
      super(builder);
    }
    private ListResponse(boolean noInit) {}
    
    private static final ListResponse defaultInstance;
    public static ListResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ListResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socklabs.elasticservices.work.WorkServiceProto.internal_static_com_socklabs_elasticservices_work_ListResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socklabs.elasticservices.work.WorkServiceProto.internal_static_com_socklabs_elasticservices_work_ListResponse_fieldAccessorTable;
    }
    
    // repeated .com.socklabs.elasticservices.work.WorkInfo work_info = 1;
    public static final int WORK_INFO_FIELD_NUMBER = 1;
    private java.util.List<com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo> workInfo_;
    public java.util.List<com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo> getWorkInfoList() {
      return workInfo_;
    }
    public java.util.List<? extends com.socklabs.elasticservices.work.WorkServiceProto.WorkInfoOrBuilder> 
        getWorkInfoOrBuilderList() {
      return workInfo_;
    }
    public int getWorkInfoCount() {
      return workInfo_.size();
    }
    public com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo getWorkInfo(int index) {
      return workInfo_.get(index);
    }
    public com.socklabs.elasticservices.work.WorkServiceProto.WorkInfoOrBuilder getWorkInfoOrBuilder(
        int index) {
      return workInfo_.get(index);
    }
    
    private void initFields() {
      workInfo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < workInfo_.size(); i++) {
        output.writeMessage(1, workInfo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < workInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, workInfo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socklabs.elasticservices.work.WorkServiceProto.ListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socklabs.elasticservices.work.WorkServiceProto.ListResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.socklabs.elasticservices.work.WorkServiceProto.ListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.socklabs.elasticservices.work.WorkServiceProto.internal_static_com_socklabs_elasticservices_work_ListResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.socklabs.elasticservices.work.WorkServiceProto.internal_static_com_socklabs_elasticservices_work_ListResponse_fieldAccessorTable;
      }
      
      // Construct using com.socklabs.elasticservices.work.WorkServiceProto.ListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWorkInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (workInfoBuilder_ == null) {
          workInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          workInfoBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socklabs.elasticservices.work.WorkServiceProto.ListResponse.getDescriptor();
      }
      
      public com.socklabs.elasticservices.work.WorkServiceProto.ListResponse getDefaultInstanceForType() {
        return com.socklabs.elasticservices.work.WorkServiceProto.ListResponse.getDefaultInstance();
      }
      
      public com.socklabs.elasticservices.work.WorkServiceProto.ListResponse build() {
        com.socklabs.elasticservices.work.WorkServiceProto.ListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.socklabs.elasticservices.work.WorkServiceProto.ListResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.socklabs.elasticservices.work.WorkServiceProto.ListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.socklabs.elasticservices.work.WorkServiceProto.ListResponse buildPartial() {
        com.socklabs.elasticservices.work.WorkServiceProto.ListResponse result = new com.socklabs.elasticservices.work.WorkServiceProto.ListResponse(this);
        int from_bitField0_ = bitField0_;
        if (workInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            workInfo_ = java.util.Collections.unmodifiableList(workInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.workInfo_ = workInfo_;
        } else {
          result.workInfo_ = workInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socklabs.elasticservices.work.WorkServiceProto.ListResponse) {
          return mergeFrom((com.socklabs.elasticservices.work.WorkServiceProto.ListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socklabs.elasticservices.work.WorkServiceProto.ListResponse other) {
        if (other == com.socklabs.elasticservices.work.WorkServiceProto.ListResponse.getDefaultInstance()) return this;
        if (workInfoBuilder_ == null) {
          if (!other.workInfo_.isEmpty()) {
            if (workInfo_.isEmpty()) {
              workInfo_ = other.workInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWorkInfoIsMutable();
              workInfo_.addAll(other.workInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.workInfo_.isEmpty()) {
            if (workInfoBuilder_.isEmpty()) {
              workInfoBuilder_.dispose();
              workInfoBuilder_ = null;
              workInfo_ = other.workInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              workInfoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWorkInfoFieldBuilder() : null;
            } else {
              workInfoBuilder_.addAllMessages(other.workInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.Builder subBuilder = com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addWorkInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.socklabs.elasticservices.work.WorkInfo work_info = 1;
      private java.util.List<com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo> workInfo_ =
        java.util.Collections.emptyList();
      private void ensureWorkInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          workInfo_ = new java.util.ArrayList<com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo>(workInfo_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo, com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.Builder, com.socklabs.elasticservices.work.WorkServiceProto.WorkInfoOrBuilder> workInfoBuilder_;
      
      public java.util.List<com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo> getWorkInfoList() {
        if (workInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(workInfo_);
        } else {
          return workInfoBuilder_.getMessageList();
        }
      }
      public int getWorkInfoCount() {
        if (workInfoBuilder_ == null) {
          return workInfo_.size();
        } else {
          return workInfoBuilder_.getCount();
        }
      }
      public com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo getWorkInfo(int index) {
        if (workInfoBuilder_ == null) {
          return workInfo_.get(index);
        } else {
          return workInfoBuilder_.getMessage(index);
        }
      }
      public Builder setWorkInfo(
          int index, com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo value) {
        if (workInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorkInfoIsMutable();
          workInfo_.set(index, value);
          onChanged();
        } else {
          workInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setWorkInfo(
          int index, com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.Builder builderForValue) {
        if (workInfoBuilder_ == null) {
          ensureWorkInfoIsMutable();
          workInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          workInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addWorkInfo(com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo value) {
        if (workInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorkInfoIsMutable();
          workInfo_.add(value);
          onChanged();
        } else {
          workInfoBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addWorkInfo(
          int index, com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo value) {
        if (workInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWorkInfoIsMutable();
          workInfo_.add(index, value);
          onChanged();
        } else {
          workInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addWorkInfo(
          com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.Builder builderForValue) {
        if (workInfoBuilder_ == null) {
          ensureWorkInfoIsMutable();
          workInfo_.add(builderForValue.build());
          onChanged();
        } else {
          workInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addWorkInfo(
          int index, com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.Builder builderForValue) {
        if (workInfoBuilder_ == null) {
          ensureWorkInfoIsMutable();
          workInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          workInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllWorkInfo(
          java.lang.Iterable<? extends com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo> values) {
        if (workInfoBuilder_ == null) {
          ensureWorkInfoIsMutable();
          super.addAll(values, workInfo_);
          onChanged();
        } else {
          workInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearWorkInfo() {
        if (workInfoBuilder_ == null) {
          workInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          workInfoBuilder_.clear();
        }
        return this;
      }
      public Builder removeWorkInfo(int index) {
        if (workInfoBuilder_ == null) {
          ensureWorkInfoIsMutable();
          workInfo_.remove(index);
          onChanged();
        } else {
          workInfoBuilder_.remove(index);
        }
        return this;
      }
      public com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.Builder getWorkInfoBuilder(
          int index) {
        return getWorkInfoFieldBuilder().getBuilder(index);
      }
      public com.socklabs.elasticservices.work.WorkServiceProto.WorkInfoOrBuilder getWorkInfoOrBuilder(
          int index) {
        if (workInfoBuilder_ == null) {
          return workInfo_.get(index);  } else {
          return workInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.socklabs.elasticservices.work.WorkServiceProto.WorkInfoOrBuilder> 
           getWorkInfoOrBuilderList() {
        if (workInfoBuilder_ != null) {
          return workInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(workInfo_);
        }
      }
      public com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.Builder addWorkInfoBuilder() {
        return getWorkInfoFieldBuilder().addBuilder(
            com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.getDefaultInstance());
      }
      public com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.Builder addWorkInfoBuilder(
          int index) {
        return getWorkInfoFieldBuilder().addBuilder(
            index, com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.getDefaultInstance());
      }
      public java.util.List<com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.Builder> 
           getWorkInfoBuilderList() {
        return getWorkInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo, com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.Builder, com.socklabs.elasticservices.work.WorkServiceProto.WorkInfoOrBuilder> 
          getWorkInfoFieldBuilder() {
        if (workInfoBuilder_ == null) {
          workInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo, com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.Builder, com.socklabs.elasticservices.work.WorkServiceProto.WorkInfoOrBuilder>(
                  workInfo_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          workInfo_ = null;
        }
        return workInfoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socklabs.elasticservices.work.ListResponse)
    }
    
    static {
      defaultInstance = new ListResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socklabs.elasticservices.work.ListResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socklabs_elasticservices_work_WorkInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socklabs_elasticservices_work_WorkInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socklabs_elasticservices_work_ListRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socklabs_elasticservices_work_ListRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socklabs_elasticservices_work_ListResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socklabs_elasticservices_work_ListResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,com/socklabs/elasticservices/work/work" +
      ".proto\022!com.socklabs.elasticservices.wor" +
      "k\"?\n\010WorkInfo\022\n\n\002id\030\001 \001(\t\022\r\n\005phase\030\002 \001(\t" +
      "\022\030\n\020is_shutting_down\030\003 \001(\010\"\031\n\013ListReques" +
      "t\022\n\n\002id\030\001 \003(\t\"N\n\014ListResponse\022>\n\twork_in" +
      "fo\030\001 \003(\0132+.com.socklabs.elasticservices." +
      "work.WorkInfoB7\n!com.socklabs.elasticser" +
      "vices.workB\020WorkServiceProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_socklabs_elasticservices_work_WorkInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_socklabs_elasticservices_work_WorkInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socklabs_elasticservices_work_WorkInfo_descriptor,
              new java.lang.String[] { "Id", "Phase", "IsShuttingDown", },
              com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.class,
              com.socklabs.elasticservices.work.WorkServiceProto.WorkInfo.Builder.class);
          internal_static_com_socklabs_elasticservices_work_ListRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_socklabs_elasticservices_work_ListRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socklabs_elasticservices_work_ListRequest_descriptor,
              new java.lang.String[] { "Id", },
              com.socklabs.elasticservices.work.WorkServiceProto.ListRequest.class,
              com.socklabs.elasticservices.work.WorkServiceProto.ListRequest.Builder.class);
          internal_static_com_socklabs_elasticservices_work_ListResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_socklabs_elasticservices_work_ListResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socklabs_elasticservices_work_ListResponse_descriptor,
              new java.lang.String[] { "WorkInfo", },
              com.socklabs.elasticservices.work.WorkServiceProto.ListResponse.class,
              com.socklabs.elasticservices.work.WorkServiceProto.ListResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
