// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/socklabs/elasticservices/core/test.proto

package com.socklabs.elasticservices.core;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FooOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint64 current_time = 1;
    boolean hasCurrentTime();
    long getCurrentTime();
  }
  public static final class Foo extends
      com.google.protobuf.GeneratedMessage
      implements FooOrBuilder {
    // Use Foo.newBuilder() to construct.
    private Foo(Builder builder) {
      super(builder);
    }
    private Foo(boolean noInit) {}
    
    private static final Foo defaultInstance;
    public static Foo getDefaultInstance() {
      return defaultInstance;
    }
    
    public Foo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Foo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Foo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint64 current_time = 1;
    public static final int CURRENT_TIME_FIELD_NUMBER = 1;
    private long currentTime_;
    public boolean hasCurrentTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getCurrentTime() {
      return currentTime_;
    }
    
    private void initFields() {
      currentTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, currentTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, currentTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.socklabs.elasticservices.core.TestProto.Foo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Foo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Foo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Foo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Foo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Foo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Foo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socklabs.elasticservices.core.TestProto.Foo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socklabs.elasticservices.core.TestProto.Foo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Foo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socklabs.elasticservices.core.TestProto.Foo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.socklabs.elasticservices.core.TestProto.FooOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Foo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Foo_fieldAccessorTable;
      }
      
      // Construct using com.socklabs.elasticservices.core.TestProto.Foo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        currentTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socklabs.elasticservices.core.TestProto.Foo.getDescriptor();
      }
      
      public com.socklabs.elasticservices.core.TestProto.Foo getDefaultInstanceForType() {
        return com.socklabs.elasticservices.core.TestProto.Foo.getDefaultInstance();
      }
      
      public com.socklabs.elasticservices.core.TestProto.Foo build() {
        com.socklabs.elasticservices.core.TestProto.Foo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.socklabs.elasticservices.core.TestProto.Foo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.socklabs.elasticservices.core.TestProto.Foo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.socklabs.elasticservices.core.TestProto.Foo buildPartial() {
        com.socklabs.elasticservices.core.TestProto.Foo result = new com.socklabs.elasticservices.core.TestProto.Foo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.currentTime_ = currentTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socklabs.elasticservices.core.TestProto.Foo) {
          return mergeFrom((com.socklabs.elasticservices.core.TestProto.Foo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socklabs.elasticservices.core.TestProto.Foo other) {
        if (other == com.socklabs.elasticservices.core.TestProto.Foo.getDefaultInstance()) return this;
        if (other.hasCurrentTime()) {
          setCurrentTime(other.getCurrentTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              currentTime_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint64 current_time = 1;
      private long currentTime_ ;
      public boolean hasCurrentTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getCurrentTime() {
        return currentTime_;
      }
      public Builder setCurrentTime(long value) {
        bitField0_ |= 0x00000001;
        currentTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrentTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currentTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socklabs.elasticservices.core.Foo)
    }
    
    static {
      defaultInstance = new Foo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socklabs.elasticservices.core.Foo)
  }
  
  public interface BarOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.socklabs.elasticservices.core.Baz bazi = 1;
    java.util.List<com.socklabs.elasticservices.core.TestProto.Baz> 
        getBaziList();
    com.socklabs.elasticservices.core.TestProto.Baz getBazi(int index);
    int getBaziCount();
    java.util.List<? extends com.socklabs.elasticservices.core.TestProto.BazOrBuilder> 
        getBaziOrBuilderList();
    com.socklabs.elasticservices.core.TestProto.BazOrBuilder getBaziOrBuilder(
        int index);
  }
  public static final class Bar extends
      com.google.protobuf.GeneratedMessage
      implements BarOrBuilder {
    // Use Bar.newBuilder() to construct.
    private Bar(Builder builder) {
      super(builder);
    }
    private Bar(boolean noInit) {}
    
    private static final Bar defaultInstance;
    public static Bar getDefaultInstance() {
      return defaultInstance;
    }
    
    public Bar getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Bar_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Bar_fieldAccessorTable;
    }
    
    // repeated .com.socklabs.elasticservices.core.Baz bazi = 1;
    public static final int BAZI_FIELD_NUMBER = 1;
    private java.util.List<com.socklabs.elasticservices.core.TestProto.Baz> bazi_;
    public java.util.List<com.socklabs.elasticservices.core.TestProto.Baz> getBaziList() {
      return bazi_;
    }
    public java.util.List<? extends com.socklabs.elasticservices.core.TestProto.BazOrBuilder> 
        getBaziOrBuilderList() {
      return bazi_;
    }
    public int getBaziCount() {
      return bazi_.size();
    }
    public com.socklabs.elasticservices.core.TestProto.Baz getBazi(int index) {
      return bazi_.get(index);
    }
    public com.socklabs.elasticservices.core.TestProto.BazOrBuilder getBaziOrBuilder(
        int index) {
      return bazi_.get(index);
    }
    
    private void initFields() {
      bazi_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < bazi_.size(); i++) {
        output.writeMessage(1, bazi_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < bazi_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, bazi_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.socklabs.elasticservices.core.TestProto.Bar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Bar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Bar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Bar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Bar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Bar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Bar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socklabs.elasticservices.core.TestProto.Bar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socklabs.elasticservices.core.TestProto.Bar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Bar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socklabs.elasticservices.core.TestProto.Bar prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.socklabs.elasticservices.core.TestProto.BarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Bar_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Bar_fieldAccessorTable;
      }
      
      // Construct using com.socklabs.elasticservices.core.TestProto.Bar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBaziFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (baziBuilder_ == null) {
          bazi_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          baziBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socklabs.elasticservices.core.TestProto.Bar.getDescriptor();
      }
      
      public com.socklabs.elasticservices.core.TestProto.Bar getDefaultInstanceForType() {
        return com.socklabs.elasticservices.core.TestProto.Bar.getDefaultInstance();
      }
      
      public com.socklabs.elasticservices.core.TestProto.Bar build() {
        com.socklabs.elasticservices.core.TestProto.Bar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.socklabs.elasticservices.core.TestProto.Bar buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.socklabs.elasticservices.core.TestProto.Bar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.socklabs.elasticservices.core.TestProto.Bar buildPartial() {
        com.socklabs.elasticservices.core.TestProto.Bar result = new com.socklabs.elasticservices.core.TestProto.Bar(this);
        int from_bitField0_ = bitField0_;
        if (baziBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            bazi_ = java.util.Collections.unmodifiableList(bazi_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.bazi_ = bazi_;
        } else {
          result.bazi_ = baziBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socklabs.elasticservices.core.TestProto.Bar) {
          return mergeFrom((com.socklabs.elasticservices.core.TestProto.Bar)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socklabs.elasticservices.core.TestProto.Bar other) {
        if (other == com.socklabs.elasticservices.core.TestProto.Bar.getDefaultInstance()) return this;
        if (baziBuilder_ == null) {
          if (!other.bazi_.isEmpty()) {
            if (bazi_.isEmpty()) {
              bazi_ = other.bazi_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBaziIsMutable();
              bazi_.addAll(other.bazi_);
            }
            onChanged();
          }
        } else {
          if (!other.bazi_.isEmpty()) {
            if (baziBuilder_.isEmpty()) {
              baziBuilder_.dispose();
              baziBuilder_ = null;
              bazi_ = other.bazi_;
              bitField0_ = (bitField0_ & ~0x00000001);
              baziBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBaziFieldBuilder() : null;
            } else {
              baziBuilder_.addAllMessages(other.bazi_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.socklabs.elasticservices.core.TestProto.Baz.Builder subBuilder = com.socklabs.elasticservices.core.TestProto.Baz.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBazi(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.socklabs.elasticservices.core.Baz bazi = 1;
      private java.util.List<com.socklabs.elasticservices.core.TestProto.Baz> bazi_ =
        java.util.Collections.emptyList();
      private void ensureBaziIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          bazi_ = new java.util.ArrayList<com.socklabs.elasticservices.core.TestProto.Baz>(bazi_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.socklabs.elasticservices.core.TestProto.Baz, com.socklabs.elasticservices.core.TestProto.Baz.Builder, com.socklabs.elasticservices.core.TestProto.BazOrBuilder> baziBuilder_;
      
      public java.util.List<com.socklabs.elasticservices.core.TestProto.Baz> getBaziList() {
        if (baziBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bazi_);
        } else {
          return baziBuilder_.getMessageList();
        }
      }
      public int getBaziCount() {
        if (baziBuilder_ == null) {
          return bazi_.size();
        } else {
          return baziBuilder_.getCount();
        }
      }
      public com.socklabs.elasticservices.core.TestProto.Baz getBazi(int index) {
        if (baziBuilder_ == null) {
          return bazi_.get(index);
        } else {
          return baziBuilder_.getMessage(index);
        }
      }
      public Builder setBazi(
          int index, com.socklabs.elasticservices.core.TestProto.Baz value) {
        if (baziBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBaziIsMutable();
          bazi_.set(index, value);
          onChanged();
        } else {
          baziBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setBazi(
          int index, com.socklabs.elasticservices.core.TestProto.Baz.Builder builderForValue) {
        if (baziBuilder_ == null) {
          ensureBaziIsMutable();
          bazi_.set(index, builderForValue.build());
          onChanged();
        } else {
          baziBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addBazi(com.socklabs.elasticservices.core.TestProto.Baz value) {
        if (baziBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBaziIsMutable();
          bazi_.add(value);
          onChanged();
        } else {
          baziBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addBazi(
          int index, com.socklabs.elasticservices.core.TestProto.Baz value) {
        if (baziBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBaziIsMutable();
          bazi_.add(index, value);
          onChanged();
        } else {
          baziBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addBazi(
          com.socklabs.elasticservices.core.TestProto.Baz.Builder builderForValue) {
        if (baziBuilder_ == null) {
          ensureBaziIsMutable();
          bazi_.add(builderForValue.build());
          onChanged();
        } else {
          baziBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addBazi(
          int index, com.socklabs.elasticservices.core.TestProto.Baz.Builder builderForValue) {
        if (baziBuilder_ == null) {
          ensureBaziIsMutable();
          bazi_.add(index, builderForValue.build());
          onChanged();
        } else {
          baziBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllBazi(
          java.lang.Iterable<? extends com.socklabs.elasticservices.core.TestProto.Baz> values) {
        if (baziBuilder_ == null) {
          ensureBaziIsMutable();
          super.addAll(values, bazi_);
          onChanged();
        } else {
          baziBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearBazi() {
        if (baziBuilder_ == null) {
          bazi_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          baziBuilder_.clear();
        }
        return this;
      }
      public Builder removeBazi(int index) {
        if (baziBuilder_ == null) {
          ensureBaziIsMutable();
          bazi_.remove(index);
          onChanged();
        } else {
          baziBuilder_.remove(index);
        }
        return this;
      }
      public com.socklabs.elasticservices.core.TestProto.Baz.Builder getBaziBuilder(
          int index) {
        return getBaziFieldBuilder().getBuilder(index);
      }
      public com.socklabs.elasticservices.core.TestProto.BazOrBuilder getBaziOrBuilder(
          int index) {
        if (baziBuilder_ == null) {
          return bazi_.get(index);  } else {
          return baziBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.socklabs.elasticservices.core.TestProto.BazOrBuilder> 
           getBaziOrBuilderList() {
        if (baziBuilder_ != null) {
          return baziBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bazi_);
        }
      }
      public com.socklabs.elasticservices.core.TestProto.Baz.Builder addBaziBuilder() {
        return getBaziFieldBuilder().addBuilder(
            com.socklabs.elasticservices.core.TestProto.Baz.getDefaultInstance());
      }
      public com.socklabs.elasticservices.core.TestProto.Baz.Builder addBaziBuilder(
          int index) {
        return getBaziFieldBuilder().addBuilder(
            index, com.socklabs.elasticservices.core.TestProto.Baz.getDefaultInstance());
      }
      public java.util.List<com.socklabs.elasticservices.core.TestProto.Baz.Builder> 
           getBaziBuilderList() {
        return getBaziFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.socklabs.elasticservices.core.TestProto.Baz, com.socklabs.elasticservices.core.TestProto.Baz.Builder, com.socklabs.elasticservices.core.TestProto.BazOrBuilder> 
          getBaziFieldBuilder() {
        if (baziBuilder_ == null) {
          baziBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.socklabs.elasticservices.core.TestProto.Baz, com.socklabs.elasticservices.core.TestProto.Baz.Builder, com.socklabs.elasticservices.core.TestProto.BazOrBuilder>(
                  bazi_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          bazi_ = null;
        }
        return baziBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socklabs.elasticservices.core.Bar)
    }
    
    static {
      defaultInstance = new Bar(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socklabs.elasticservices.core.Bar)
  }
  
  public interface BazOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string value = 1;
    boolean hasValue();
    String getValue();
    
    // repeated .com.socklabs.elasticservices.core.Baz.Attribute attribute = 2;
    java.util.List<com.socklabs.elasticservices.core.TestProto.Baz.Attribute> 
        getAttributeList();
    com.socklabs.elasticservices.core.TestProto.Baz.Attribute getAttribute(int index);
    int getAttributeCount();
    java.util.List<? extends com.socklabs.elasticservices.core.TestProto.Baz.AttributeOrBuilder> 
        getAttributeOrBuilderList();
    com.socklabs.elasticservices.core.TestProto.Baz.AttributeOrBuilder getAttributeOrBuilder(
        int index);
  }
  public static final class Baz extends
      com.google.protobuf.GeneratedMessage
      implements BazOrBuilder {
    // Use Baz.newBuilder() to construct.
    private Baz(Builder builder) {
      super(builder);
    }
    private Baz(boolean noInit) {}
    
    private static final Baz defaultInstance;
    public static Baz getDefaultInstance() {
      return defaultInstance;
    }
    
    public Baz getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Baz_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Baz_fieldAccessorTable;
    }
    
    public interface AttributeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional string key = 1;
      boolean hasKey();
      String getKey();
      
      // optional string value = 2;
      boolean hasValue();
      String getValue();
    }
    public static final class Attribute extends
        com.google.protobuf.GeneratedMessage
        implements AttributeOrBuilder {
      // Use Attribute.newBuilder() to construct.
      private Attribute(Builder builder) {
        super(builder);
      }
      private Attribute(boolean noInit) {}
      
      private static final Attribute defaultInstance;
      public static Attribute getDefaultInstance() {
        return defaultInstance;
      }
      
      public Attribute getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Baz_Attribute_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Baz_Attribute_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional string key = 1;
      public static final int KEY_FIELD_NUMBER = 1;
      private java.lang.Object key_;
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            key_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private java.lang.Object value_;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            value_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        key_ = "";
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.socklabs.elasticservices.core.TestProto.Baz.Attribute parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.socklabs.elasticservices.core.TestProto.Baz.Attribute parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.socklabs.elasticservices.core.TestProto.Baz.Attribute parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.socklabs.elasticservices.core.TestProto.Baz.Attribute parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.socklabs.elasticservices.core.TestProto.Baz.Attribute parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.socklabs.elasticservices.core.TestProto.Baz.Attribute parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.socklabs.elasticservices.core.TestProto.Baz.Attribute parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.socklabs.elasticservices.core.TestProto.Baz.Attribute parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.socklabs.elasticservices.core.TestProto.Baz.Attribute parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.socklabs.elasticservices.core.TestProto.Baz.Attribute parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.socklabs.elasticservices.core.TestProto.Baz.Attribute prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.socklabs.elasticservices.core.TestProto.Baz.AttributeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Baz_Attribute_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Baz_Attribute_fieldAccessorTable;
        }
        
        // Construct using com.socklabs.elasticservices.core.TestProto.Baz.Attribute.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.socklabs.elasticservices.core.TestProto.Baz.Attribute.getDescriptor();
        }
        
        public com.socklabs.elasticservices.core.TestProto.Baz.Attribute getDefaultInstanceForType() {
          return com.socklabs.elasticservices.core.TestProto.Baz.Attribute.getDefaultInstance();
        }
        
        public com.socklabs.elasticservices.core.TestProto.Baz.Attribute build() {
          com.socklabs.elasticservices.core.TestProto.Baz.Attribute result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.socklabs.elasticservices.core.TestProto.Baz.Attribute buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.socklabs.elasticservices.core.TestProto.Baz.Attribute result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.socklabs.elasticservices.core.TestProto.Baz.Attribute buildPartial() {
          com.socklabs.elasticservices.core.TestProto.Baz.Attribute result = new com.socklabs.elasticservices.core.TestProto.Baz.Attribute(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.socklabs.elasticservices.core.TestProto.Baz.Attribute) {
            return mergeFrom((com.socklabs.elasticservices.core.TestProto.Baz.Attribute)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.socklabs.elasticservices.core.TestProto.Baz.Attribute other) {
          if (other == com.socklabs.elasticservices.core.TestProto.Baz.Attribute.getDefaultInstance()) return this;
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                key_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                value_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional string key = 1;
        private java.lang.Object key_ = "";
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setKey(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        void setKey(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
        }
        
        // optional string value = 2;
        private java.lang.Object value_ = "";
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setValue(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        void setValue(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:com.socklabs.elasticservices.core.Baz.Attribute)
      }
      
      static {
        defaultInstance = new Attribute(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.socklabs.elasticservices.core.Baz.Attribute)
    }
    
    private int bitField0_;
    // optional string value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .com.socklabs.elasticservices.core.Baz.Attribute attribute = 2;
    public static final int ATTRIBUTE_FIELD_NUMBER = 2;
    private java.util.List<com.socklabs.elasticservices.core.TestProto.Baz.Attribute> attribute_;
    public java.util.List<com.socklabs.elasticservices.core.TestProto.Baz.Attribute> getAttributeList() {
      return attribute_;
    }
    public java.util.List<? extends com.socklabs.elasticservices.core.TestProto.Baz.AttributeOrBuilder> 
        getAttributeOrBuilderList() {
      return attribute_;
    }
    public int getAttributeCount() {
      return attribute_.size();
    }
    public com.socklabs.elasticservices.core.TestProto.Baz.Attribute getAttribute(int index) {
      return attribute_.get(index);
    }
    public com.socklabs.elasticservices.core.TestProto.Baz.AttributeOrBuilder getAttributeOrBuilder(
        int index) {
      return attribute_.get(index);
    }
    
    private void initFields() {
      value_ = "";
      attribute_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getValueBytes());
      }
      for (int i = 0; i < attribute_.size(); i++) {
        output.writeMessage(2, attribute_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getValueBytes());
      }
      for (int i = 0; i < attribute_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, attribute_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.socklabs.elasticservices.core.TestProto.Baz parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Baz parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Baz parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Baz parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Baz parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Baz parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Baz parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socklabs.elasticservices.core.TestProto.Baz parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.socklabs.elasticservices.core.TestProto.Baz parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.socklabs.elasticservices.core.TestProto.Baz parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.socklabs.elasticservices.core.TestProto.Baz prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.socklabs.elasticservices.core.TestProto.BazOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Baz_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.socklabs.elasticservices.core.TestProto.internal_static_com_socklabs_elasticservices_core_Baz_fieldAccessorTable;
      }
      
      // Construct using com.socklabs.elasticservices.core.TestProto.Baz.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttributeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (attributeBuilder_ == null) {
          attribute_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          attributeBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socklabs.elasticservices.core.TestProto.Baz.getDescriptor();
      }
      
      public com.socklabs.elasticservices.core.TestProto.Baz getDefaultInstanceForType() {
        return com.socklabs.elasticservices.core.TestProto.Baz.getDefaultInstance();
      }
      
      public com.socklabs.elasticservices.core.TestProto.Baz build() {
        com.socklabs.elasticservices.core.TestProto.Baz result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.socklabs.elasticservices.core.TestProto.Baz buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.socklabs.elasticservices.core.TestProto.Baz result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.socklabs.elasticservices.core.TestProto.Baz buildPartial() {
        com.socklabs.elasticservices.core.TestProto.Baz result = new com.socklabs.elasticservices.core.TestProto.Baz(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        if (attributeBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            attribute_ = java.util.Collections.unmodifiableList(attribute_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.attribute_ = attribute_;
        } else {
          result.attribute_ = attributeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socklabs.elasticservices.core.TestProto.Baz) {
          return mergeFrom((com.socklabs.elasticservices.core.TestProto.Baz)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.socklabs.elasticservices.core.TestProto.Baz other) {
        if (other == com.socklabs.elasticservices.core.TestProto.Baz.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (attributeBuilder_ == null) {
          if (!other.attribute_.isEmpty()) {
            if (attribute_.isEmpty()) {
              attribute_ = other.attribute_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAttributeIsMutable();
              attribute_.addAll(other.attribute_);
            }
            onChanged();
          }
        } else {
          if (!other.attribute_.isEmpty()) {
            if (attributeBuilder_.isEmpty()) {
              attributeBuilder_.dispose();
              attributeBuilder_ = null;
              attribute_ = other.attribute_;
              bitField0_ = (bitField0_ & ~0x00000002);
              attributeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttributeFieldBuilder() : null;
            } else {
              attributeBuilder_.addAllMessages(other.attribute_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              value_ = input.readBytes();
              break;
            }
            case 18: {
              com.socklabs.elasticservices.core.TestProto.Baz.Attribute.Builder subBuilder = com.socklabs.elasticservices.core.TestProto.Baz.Attribute.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAttribute(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string value = 1;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
      }
      
      // repeated .com.socklabs.elasticservices.core.Baz.Attribute attribute = 2;
      private java.util.List<com.socklabs.elasticservices.core.TestProto.Baz.Attribute> attribute_ =
        java.util.Collections.emptyList();
      private void ensureAttributeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          attribute_ = new java.util.ArrayList<com.socklabs.elasticservices.core.TestProto.Baz.Attribute>(attribute_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.socklabs.elasticservices.core.TestProto.Baz.Attribute, com.socklabs.elasticservices.core.TestProto.Baz.Attribute.Builder, com.socklabs.elasticservices.core.TestProto.Baz.AttributeOrBuilder> attributeBuilder_;
      
      public java.util.List<com.socklabs.elasticservices.core.TestProto.Baz.Attribute> getAttributeList() {
        if (attributeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attribute_);
        } else {
          return attributeBuilder_.getMessageList();
        }
      }
      public int getAttributeCount() {
        if (attributeBuilder_ == null) {
          return attribute_.size();
        } else {
          return attributeBuilder_.getCount();
        }
      }
      public com.socklabs.elasticservices.core.TestProto.Baz.Attribute getAttribute(int index) {
        if (attributeBuilder_ == null) {
          return attribute_.get(index);
        } else {
          return attributeBuilder_.getMessage(index);
        }
      }
      public Builder setAttribute(
          int index, com.socklabs.elasticservices.core.TestProto.Baz.Attribute value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeIsMutable();
          attribute_.set(index, value);
          onChanged();
        } else {
          attributeBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAttribute(
          int index, com.socklabs.elasticservices.core.TestProto.Baz.Attribute.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAttribute(com.socklabs.elasticservices.core.TestProto.Baz.Attribute value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeIsMutable();
          attribute_.add(value);
          onChanged();
        } else {
          attributeBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAttribute(
          int index, com.socklabs.elasticservices.core.TestProto.Baz.Attribute value) {
        if (attributeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeIsMutable();
          attribute_.add(index, value);
          onChanged();
        } else {
          attributeBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAttribute(
          com.socklabs.elasticservices.core.TestProto.Baz.Attribute.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.add(builderForValue.build());
          onChanged();
        } else {
          attributeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAttribute(
          int index, com.socklabs.elasticservices.core.TestProto.Baz.Attribute.Builder builderForValue) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAttribute(
          java.lang.Iterable<? extends com.socklabs.elasticservices.core.TestProto.Baz.Attribute> values) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          super.addAll(values, attribute_);
          onChanged();
        } else {
          attributeBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAttribute() {
        if (attributeBuilder_ == null) {
          attribute_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          attributeBuilder_.clear();
        }
        return this;
      }
      public Builder removeAttribute(int index) {
        if (attributeBuilder_ == null) {
          ensureAttributeIsMutable();
          attribute_.remove(index);
          onChanged();
        } else {
          attributeBuilder_.remove(index);
        }
        return this;
      }
      public com.socklabs.elasticservices.core.TestProto.Baz.Attribute.Builder getAttributeBuilder(
          int index) {
        return getAttributeFieldBuilder().getBuilder(index);
      }
      public com.socklabs.elasticservices.core.TestProto.Baz.AttributeOrBuilder getAttributeOrBuilder(
          int index) {
        if (attributeBuilder_ == null) {
          return attribute_.get(index);  } else {
          return attributeBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.socklabs.elasticservices.core.TestProto.Baz.AttributeOrBuilder> 
           getAttributeOrBuilderList() {
        if (attributeBuilder_ != null) {
          return attributeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attribute_);
        }
      }
      public com.socklabs.elasticservices.core.TestProto.Baz.Attribute.Builder addAttributeBuilder() {
        return getAttributeFieldBuilder().addBuilder(
            com.socklabs.elasticservices.core.TestProto.Baz.Attribute.getDefaultInstance());
      }
      public com.socklabs.elasticservices.core.TestProto.Baz.Attribute.Builder addAttributeBuilder(
          int index) {
        return getAttributeFieldBuilder().addBuilder(
            index, com.socklabs.elasticservices.core.TestProto.Baz.Attribute.getDefaultInstance());
      }
      public java.util.List<com.socklabs.elasticservices.core.TestProto.Baz.Attribute.Builder> 
           getAttributeBuilderList() {
        return getAttributeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.socklabs.elasticservices.core.TestProto.Baz.Attribute, com.socklabs.elasticservices.core.TestProto.Baz.Attribute.Builder, com.socklabs.elasticservices.core.TestProto.Baz.AttributeOrBuilder> 
          getAttributeFieldBuilder() {
        if (attributeBuilder_ == null) {
          attributeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.socklabs.elasticservices.core.TestProto.Baz.Attribute, com.socklabs.elasticservices.core.TestProto.Baz.Attribute.Builder, com.socklabs.elasticservices.core.TestProto.Baz.AttributeOrBuilder>(
                  attribute_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          attribute_ = null;
        }
        return attributeBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.socklabs.elasticservices.core.Baz)
    }
    
    static {
      defaultInstance = new Baz(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.socklabs.elasticservices.core.Baz)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socklabs_elasticservices_core_Foo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socklabs_elasticservices_core_Foo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socklabs_elasticservices_core_Bar_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socklabs_elasticservices_core_Bar_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socklabs_elasticservices_core_Baz_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socklabs_elasticservices_core_Baz_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_socklabs_elasticservices_core_Baz_Attribute_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_socklabs_elasticservices_core_Baz_Attribute_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,com/socklabs/elasticservices/core/test" +
      ".proto\022!com.socklabs.elasticservices.cor" +
      "e\"\033\n\003Foo\022\024\n\014current_time\030\001 \001(\004\";\n\003Bar\0224\n" +
      "\004bazi\030\001 \003(\0132&.com.socklabs.elasticservic" +
      "es.core.Baz\"\202\001\n\003Baz\022\r\n\005value\030\001 \001(\t\022C\n\tat" +
      "tribute\030\002 \003(\01320.com.socklabs.elasticserv" +
      "ices.core.Baz.Attribute\032\'\n\tAttribute\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\tB3\n!com.socklabs" +
      ".elasticservices.coreB\tTestProtoH\001\210\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_socklabs_elasticservices_core_Foo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_socklabs_elasticservices_core_Foo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socklabs_elasticservices_core_Foo_descriptor,
              new java.lang.String[] { "CurrentTime", },
              com.socklabs.elasticservices.core.TestProto.Foo.class,
              com.socklabs.elasticservices.core.TestProto.Foo.Builder.class);
          internal_static_com_socklabs_elasticservices_core_Bar_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_socklabs_elasticservices_core_Bar_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socklabs_elasticservices_core_Bar_descriptor,
              new java.lang.String[] { "Bazi", },
              com.socklabs.elasticservices.core.TestProto.Bar.class,
              com.socklabs.elasticservices.core.TestProto.Bar.Builder.class);
          internal_static_com_socklabs_elasticservices_core_Baz_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_socklabs_elasticservices_core_Baz_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socklabs_elasticservices_core_Baz_descriptor,
              new java.lang.String[] { "Value", "Attribute", },
              com.socklabs.elasticservices.core.TestProto.Baz.class,
              com.socklabs.elasticservices.core.TestProto.Baz.Builder.class);
          internal_static_com_socklabs_elasticservices_core_Baz_Attribute_descriptor =
            internal_static_com_socklabs_elasticservices_core_Baz_descriptor.getNestedTypes().get(0);
          internal_static_com_socklabs_elasticservices_core_Baz_Attribute_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_socklabs_elasticservices_core_Baz_Attribute_descriptor,
              new java.lang.String[] { "Key", "Value", },
              com.socklabs.elasticservices.core.TestProto.Baz.Attribute.class,
              com.socklabs.elasticservices.core.TestProto.Baz.Attribute.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
